### ISSUE TITLE
ASG associated load balancer still fails

### ISSUE THREAD

**Issue by lukaspour** [telia-oss/terraform-aws-ecs-fargate#5]
I am still getting:
```
* aws_ecs_service.service: InvalidParameterException: The target group with targetGroupArn arn:aws:elasticloadbalancing:eu-west-1:770547935752:targetgroup/tf-20181101093848291700000004/5a67d904798508fe does not have an associated load balancer.
    status code: 400, request id: 42cf007b-deb1-11e8-b840-f320b8a37183 "cbm-api"
```
I saw the code but I guess the dependency with load balancer is missing.

**Comment by itsdalmo** [comment]
Not sure what is the latest workaround for this issue, but there is a difference between `depends_on` for the service in the regular ECS module and the fargate one:
- ECS: https://github.com/telia-oss/terraform-aws-ecs/blob/master/modules/service/main.tf#L31
- Fargate: https://github.com/telia-oss/terraform-aws-ecs-fargate/blob/master/main.tf#L140

According to [this comment](https://github.com/cds-snc/aws-ecs-fargate/issues/1#issuecomment-472822250), adding `depends_on = ["aws_alb_target_group.alb_target_group"]` should solve it (as done in the regular ECS module), and according to [another comment](https://github.com/cds-snc/aws-ecs-fargate/issues/1#issuecomment-470692240) we need the target group to depend on the ALB. We could try them separately, or just do both to be safe? 😅 

Assume you are still seeing this issue @lukaspour?

**Comment by itsdalmo** [comment]
Closing issue since it is stale.
